### PR TITLE
MIRI_IFU_YSOs_in_the_LMC Notebook

### PR DESCRIPTION
**Pull request by inayak**
Introducing MIRI_IFU_YSOs_in_the_LMC to JDat

### CODE REVIEW

**Comment by tracy-beck** [comment]
Feedback on MIRI YSOs Notebook:

Technical problems:
1 - requirements file installation failed to run, got error: ERROR: No matching distribution found for jwst==0.16.2 (from -r requirements.txt (line 4))
This error is occurring because the jwst package does not have a pip install released.  Developers note that the requirements.txt file needs to be updated for the jwst package definition to say:
jwst @ git+https://github.com/spacetelescope/jwst.git@0.16.2

 2 - after I ran the requirements file successfully I got ...  jupyter-notebook: command not found    It seems that something in loading the requirements packages obliterated my notebook access.  Before I ran the requirements file pip/install updates I was able to bring up and look at the DA notebook in my test environment with no problem.
--> I was able to get around this by adding jupyterlab==2.2.0 to the end of the requirements.txt file so that jupyter was installed in my test environment.

Science Notes/considerations on running the notebook:

Comment - it's neat and interesting to see the use of the spectral-cube routines here - thanks for the demo, Isha!  😊

General comment - Suggest addition of a 'science abstract' or several sentences describing the science to clarify the purpose of the notebook/observations.  Intro currently says "The purpose of this notebook is to use photutils to automatically detect point sources and extract photometry".  & That is a technical goal of the notebook rather than science - what will the point sources show or tell us?  & Perhaps add a sentence or two describing what the ALMA CO data are and what they show (presumably envelope emission from YSOs).  & Also the Spitzer data - not everyone that sees this notebook is likely to be familiar with characteristics of YSOs at these wavelengths.

Also add a message about how these data are similar to or relate to JWST MIRI science.  😊

In the cell following the text that says:  "Setup output directory for figures and spectra"
This is something that needs to be configured by users and it seems rather buried here. I think this should be at the top of the notebook following the import statements - with clear text saying that users need to update this to be their own paths.

In the cell following the text that reads: "Make a 2D image from the 3D cube either with average, median, or sum"
- remove code that is commented out.
Also in the same cell, I get the error.
ValueError: This function (<function BaseSpectralCube.sum at 0x125b43c20>) requires loading the entire cube into memory, and the cube is large (448573440 pixels), so by default we disable this operation. To enable the operation, set `cube.allow_huge_operations=True` and try again.  Alternatively, you may want to consider using an approach that does not load the whole cube into memory by specifying how='slice' or how='ray'.  See https://spectral-cube.readthedocs.io/en/latest/big_data.html for details.
I ran the prior cell that has the 'cube.allow_huge_operations=True' but it seems it didn't matter.  I tried running the following cell but the plot was never created.  
--> I realize that the notebook takes a very long time to read/sum the cube into memory.  & I get this error after several minutes of trying to get the cell to run.  I tried it again and again, it finally worked - but it took three tries to get this to work without giving the above error.  So - it would be good to maybe include some text in the prior markup cell that says the cube can take a long time to load?  I'm not sure why it barfed twice for me before the sum worked properly.

- Some nice plots!  😊👍

- The cell "Extract and plot spectrum of all sources" can also take a while to run.  In the markup cell it would be good to mention this, and note that the cell is done when plots are made for all four targets.

- In "Make a table for the extracted source" - uncomment the included code or remove it.

- In the code cell following: "Use Spitzer IRS YSO Spectra from Here on Out For Science Test Cases"
the "YSO1" data is read in twice, thus overwriting the first dataset!  But it seems that maybe the YSO2 file is never used?

- The continuum fit to the Spitzer data still seems questionable, the broad, wavy up/down shape of the spectrum shortward of 20 microns is probably defined by silicates+ices.  It looks like the green curve that is fitting in the 5-13 micron spectral range is not taking into account the 10 micron silicate absorption feature, and so the continuum is vastly underestimated.  The curve here should really only fit the 5-7.5 micron and ~13-14 micron region because the silicate absorption is very broad.  Similarly the long wavelength curve is fitting to the broad 18 micron feature and practically removing it from the fit as a result.  So, I think these current fits are not modeling the true underlying continuum and over-subtract dust features by a good amount.  I would be curious to see what you get if you fit only to likely continuum regions - 5-7.5 microns, 13-14 microns, maybe 24-26microns? 

-I'm having a difficult time following the emission/absorption line searches.  It seems that the 'emission lines' are areas that are positive flux, and the 'absorption lines' are negative?  Why are emission/absorption lines being found every ~10th of a micron or less in some spectral regions?  E.g., 13.0 to 13.6 microns, where that whole spectral region is negative?  YSO emission/absorption features from dust, ices and PAHs are very broad by most line fitting standards.  What are the parameters that go into identifying fit lines?  Could the expected width of a feature be used to better identify true features in the spectra?

- I think a simple positive/negative line search would only work well when you have very accurate continuum subtraction with lines that aren't very broad and super-imposed on each other.  E.g., when you over subtract the continuum in the 10 micron silicate spectral region, the PAH's can't show up as positive flux. The 15.3 micron ice absorption feature looks like its there, but since the continuum was undersubtracted in this region it can't show up in a negative flux auto-search?  Some of the bumps and wiggles on top of the broad structures are likely real.  When features are blended and on top of the broad silicate absorptions then it seems difficult/impossible to pick out multiple features without modeling and removing the broad dust.  Patrick pointed to some ice/dust/pah models and it seems that these YSOs are a case where simultaneous fitting of continuum plus dust features is probably very important?

- One way to better do a search on the broad lines in the residual curve might be to have a look-up table or array definition that has the central wavelength of an astrophysical feature plus the approximate width.  You could do a linear fit to the continuum residual by fitting the spectra at locations positive and negative to the line width, and then check to see if the center of the line is positive or negative.  E.g, if you do a linear fit to the residual curve in the spectra regions at 14.7-14.9 microns and 15.6-15.8 microns, I bet the CO2 ice feature would pop right out as an absorption detection at 15.3.  This could also allow for accurate detection of discrete, narrow lines like H2 or [NeII], [FeII] that suggest outflow activity, which would also be a good YSO diagnostic - several of those look to exist in your spectra, too.

- Is there some sort of fringing or instrument artifact that causes the structure longword of 25 microns in these IRS spectra?  If so, you might want to mention that.  Much of that spectral structure doesn't look like it's real.

In the cell prior to "Still left to do" I can't run it - get an error: NameError:
 name 'drop_dups_ice' is not defined.

- I recommend that the plot that shows the PAH, Ice/Silicates over plotted on the residuals should be moved much higher up in the notebook - before any line search is done.  & Also the 10 micron silicates and ices don't show up there.

- I can't load the data for the dendrogram so can't run the last cells.  I guess this hasn't yet been merged into the public directory.

**Comment by ibusko** [comment]
## Technical review (isha_nayak_ysos_in_the_lmc.ipynb)

### Installation

 - The `requirements.txt` file seems to be a bit old and requires revision:

   - `jwst==0.16.2` no longer installs. I was able to install the jwst package by
     specifiyng just `jwst'. This should perhaps be updated to point to the newest
     or most appropriate version.

   - a build error happens because of another package that tries to install `numpy` by
     itself. This causes a subsequent incompatibility with `wheel`. We have to force `numpy`
     to be installed first, by moving its spec to a `pre-requirements.txt` file that has to be
     run first under pip (`pip install -r pre-requirements.txt`)



### Running the notebook

 - The notebook crashed at cell #10 (Trim the cube) the first time I tried it. The fix consisted in
   moving the `allow_huge_operations=True` statement to be the first statement to be executed in the
   cell.

 - Apart from that, the notebook runs to completion.

 - In cell #3, the correct code should look like this:
   ```
   import aplpy
   from aplpy import __version__ as aplpy_version
   print("AplPY: {}".format(aplpy_version))
   ```


### Input data

  - Are properly stored in Box using redirect.


### Libraries

 - Currently available core-libraries functionalities and visualization tools are used.


### Developer notes

 - None


### PEP-8 compliance:

  - Running 'flake8' on the notebook cells results in this report

  cell  1 line 23: F811 redefinition of unused 'SpectralRegion' from line 19
  cell  6 line  1: E225 missing whitespace around operator
  cell  9 line  1: E225 missing whitespace around operator
  cell 13 line  8: E251 unexpected spaces around keyword / parameter equals
  cell 15 lines 35,53: E231 missing whitespace after ','
  cell 15 lines 42,43: E251 unexpected spaces around keyword / parameter equals
  cell 19 line 18: E222 multiple spaces after operator
  cell 19 lines 19,22: E225 missing whitespace around operator
  cell 20 line 2: E231 missing whitespace after ','
  cell 21 lines 3-5: E231 missing whitespace after ','
  cell 22 lines 8,20: E225 missing whitespace around operator
  cell 23 lines 17,46: E303 too many blank lines (2)
  cell 23 lines 23,37,53: E222 multiple spaces after operator
  cell 24 lines 17,47: E303 too many blank lines (2)
  cell 24 lines 24,54: E222 multiple spaces after operator
  cell 24 line 31: E265 block comment should start with '# '
  cell 25 lines 14,26,30: E211 whitespace before '('
  cell 25 line 35: E231 missing whitespace after ','
  cell 26 line 6: E225 missing whitespace around operator
  cell 26 lines 14,19,26,30: E211 whitespace before '('
  cell 26 line 101: E203 whitespace before ':'
  cell 26 lines 18,29,30,42,45: E231 missing whitespace after ','
  cell 26 line 44: E221 multiple spaces before operator
  cell 27 lines 14,19,26,30: E211 whitespace before '('
  cell 27 line 101: E203 whitespace before ':'
  cell 27 lines 32,48: E225 missing whitespace around operator
  cell 29 lines 2,3: E231 missing whitespace after ','
  cell 29 lines 16,25: E251 unexpected spaces around keyword / parameter equals


### CI build

 - One CI build error: `jinja2.exceptions.TemplateNotFound: nb_html.tpl`.
   I don't know the cause of this, so I suggest we deal with it later. It may go
   away by itself depending on what exact versions we have on the requirements.


### Comments

  - Suggestion: add a note to the cell where the main file download takes place
    (cell #7) , mentioning that the file can be pulled once and for all from Box
    and installed locally in the user's disk. That will save time when running the
    notebook multiple times.

  - Typo: in between cells #8 and #9 (Trim the cube): spectaral

  - Typo: in between cells #9 and #10 (Make a 2D image from the 3D cube...)
    "you will be aperture photometry" probably should be "you will be doing (or applying)
     aperture photometry"

  - Typo: title for cell #16, "Make a table for the extracted source", should probably be
    "Make a table for the extracted sources"

**Comment by inayak** [comment]
Hi Ivo,

I have gone through your comments. I need help with setting up the requirement file for numpy and I need help installing aplpy in my conda environment. I get an error when I try: pip install aplpy .

Can we meet next week so I can get help with the above two things, and then help with re-submitting my notebook. Most any day/time should work for me.

Thanks!
Best,
Isha

**Comment by ibusko** [comment]
## Technical review follow up (isha_nayak_ysos_in_the_lmc.ipynb)

### Installation

 - Works as expected.


### Running the notebook

 - Two typos in cell #2 (astrodendro and pandas_version)


### Input data

  - Are properly stored in Box using redirect.


### Libraries

 - Currently available core-libraries functionalities and visualization tools are used.


### Developer notes

 - None


### PEP-8 compliance:

 - OK


### CI build

 - There is one CI build error, but unrelated to this notebook.

**Review by ibusko — APPROVED** [review]
This notebook is good to be merged (from the technical review standpoint) as soon as the two typos mentioned in the review are addressed.

**Comment by inayak** [comment]
Hi Ivo,

I cannot get aplpy to work, and therefore cannot demo the notebook in January. I will address the comments next week. Can we also meet next week so I can get help with installing aplpy?

Thanks so much!
Best,
Isha

**Comment by ibusko** [comment]
Yes, we can meet to try to solve this issue. Although, maybe it’s related to the fact you are using python 3.9? I tried 3.7 and 3.8 with no problems.


On Dec 29, 2020, at 9:22 AM, inayak <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Ivo,

I cannot get aplpy to work, and therefore cannot demo the notebook in January. I will address the comments next week. Can we also meet next week so I can get help with installing aplpy?

Thanks so much!
Best,
Isha

**Comment by inayak** [comment]
Hi Ivo,

I got aplpy to work with python 3.8. Thank you. I will re-submit my notebook by the end of the week.

Best,
Isha

**Comment by inayak** [comment]
Hi Ivo,

I pushed it the new version with the typos fixed and a couple other things changed as well. Can you let me know you got it?

Thanks!
Best,
Isha

**Comment by ibusko** [comment]
@inayak the notebook is good to be merged now. Thanks for the fixes!

**Pull request merged**
