### PR TITLE
MRS Mstar data analysis notebook 

### PR DESCRIPTION
**Pull request by lib-j**
Notebook showing the science methodology used in the science analysis of a data cube and extracted spectra.

### CODE REVIEW

**Comment by ibusko** [comment]
I couldn't find the input file for this notebook. There is only a reference for Libby's hard disk. Maybe it's on Box, but I couldn't find it.

**Comment by astroolivine** [comment]
The notebook shows successfully how to extract a spectrum from a cube, how to analyze a spectrum of an AGB star, and how to analyze a YSO spectrum.

In the plot where the spline is fit to 20-35 microns wavelength in the AGB spectrum, I wonder if a spline fit wavelength should be added at 31 microns because the spline is currently higher than the spectrum here?  And maybe add another spline fit wavelength near 23 microns for the same reason?

Most modeling seems sound.

When the ISO spectrum is read in, is it computing the standard deviation of the error spectrum?  Why is this necessary?

There is an error message under where the optical depth of the AGB star is plotted.

The plotting looks clear to me.

Overall, it is a very long notebook, and sometimes it is a little difficult to follow, so please check that the notes are sufficient.  They usually are, but give them a quick check.

Please look over the notes for spelling/grammar issues.

In the section demonstrating how to extract from a cube, just after creating the masked cube, the comments say that the spectrum from the annulus is being extracted, but it is actually extracted from the aperture.

The next comment says the noise spectrum is being extracted.  Is the noise being computed correctly here?

Just before fitting continuum to the YSO spectrum, how does it estimate uncertainty from the spectrum itself?

Lastly, should this notebook be split into 2 (or 3) notebooks?  I was thinking: one notebook for extracting the spectrum from the cube, another notebook for the AGB star spectrum analysis, and the other notebook for the YSO spectrum analysis.  The notebook may be okay as it is currently, but I wanted to ask about this.

**Comment by lib-j** [comment]
> When the ISO spectrum is read in, is it computing the standard deviation of the error spectrum? Why is this necessary?

This seems to be the structure of the `Spectrum1D` object. I  am unable to simply use `spec = Spectrum1D(spectral_axis = wav, flux = fl, uncertainty =efl)` as this returns an error

```
spec = Spectrum1D(spectral_axis = wav, flux = fl, uncertainty = efl)

INFO: astropy:uncertainty should have attribute uncertainty_type.
INFO: uncertainty should have attribute uncertainty_type. [astropy.nddata.nddata]
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-27-61544b13113d> in <module>
     14 spec = Spectrum1D(spectral_axis = wav, flux = fl, uncertainty = StdDevUncertainty(efl))
     15 
---> 16 spec = Spectrum1D(spectral_axis = wav, flux = fl, uncertainty =efl)
     17 

~/anaconda3/envs/astro36/lib/python3.6/site-packages/specutils/spectra/spectrum1d.py in __init__(self, flux, spectral_axis, wcs, velocity_convention, rest_value, redshift, radial_velocity, **kwargs)
    132         super(Spectrum1D, self).__init__(
    133             data=flux.value if isinstance(flux, u.Quantity) else flux,
--> 134             wcs=wcs, **kwargs)
    135 
    136         # set redshift after super() - necessary because the shape-checking

~/anaconda3/envs/astro36/lib/python3.6/site-packages/astropy/nddata/nddata.py in __init__(self, data, uncertainty, mask, wcs, meta, unit, copy)
    228         self._unit = unit
    229         # Call the setter for uncertainty to further check the uncertainty
--> 230         self.uncertainty = uncertainty
    231 
    232     def __str__(self):

~/anaconda3/envs/astro36/lib/python3.6/site-packages/astropy/nddata/nddata.py in uncertainty(self, value)
    307                 # to be saved as weakref but that's done by NDUncertainty
    308                 # setter).
--> 309                 value.parent_nddata = self
    310         self._uncertainty = value

~/anaconda3/envs/astro36/lib/python3.6/site-packages/astropy/nddata/nduncertainty.py in parent_nddata(self, value)
    231                 unit_from_data = self._data_unit_to_uncertainty_unit(parent_unit)
    232                 try:
--> 233                     unit_from_data.to(self.unit)
    234                 except UnitConversionError:
    235                     raise UnitConversionError("Unit {} of uncertainty "

AttributeError: 'NoneType' object has no attribute 'to'

```

**Comment by lib-j** [comment]
> At the end of cell #22, there are two print statements that fail because the chisq variable is of type Quantity. Replacing chisq by chisq.value solves the problem.

By using numpy version 1.16.4, this value is returned as a float and therefore the notebook runs to completion.  This means more information is needed on your version of numpy (or other dependencies) as this value should have no Quantity associated with it. 

Changing the print statement to `chisq.value` results in my version failing. Therefore I have fixed this problem with stricter requirements on numpy. 

Finally, there should be a consensus on the minimum ranges of numpy and other dependencies we should be working on.

**Comment by astroolivine** [comment]
The revised notebook adequately addresses all of my comments except for one.  Just after the spectrum is extracted from the aperture, the noise in the aperture is computed.  It looks like an estimate of the noise is being made by taking the standard deviation of the fluxes of all the pixels in the aperture at each wavelength.  I accept that this could be a useful way of beginning the computation of the noise spectrum, but the noise spectrum returned is the noise spectrum for a single pixel in the aperture.  I think this means that, assuming (for simplicity) all pixels in the aperture had the same flux, one would need to multiply the noise spectrum at each wavelength by the square root of the number of pixels in the aperture at that wavelength, in order to get the correct noise spectrum.  Assuming I understand the calculation here correctly?

**Comment by eteq** [comment]
Alright, I pushed up several commits for missing dependencies, and this is running *but* there's some odd plotting error that shows up. I think it's probably `wcsaxes` related, although I can't rerpdocue so it's pretty hard to test.

**Comment by eteq** [comment]
(the last commit is a wild guess at a fix - I may have to back it out)

**Comment by astroolivine** [comment]
I asked David Law about the determination of the noise spectrum.  I think my previous suggestion would hold for extended sources but not for point sources.  For a point source, he suggested extracting the spectrum, determining a measure of the noise in a small wavelength range around a given data point, and assigning that noise measurement to that data point.  And do this for all data points in the extracted spectrum.

**Pull request merged**
