### PR TITLE
Updated PSF photometry notebook

### PR DESCRIPTION
**Pull request by mcorrenti**
Update notebook in PR #85.

### CODE REVIEW

**Comment by Vb2341** [comment]
I didn't realize that this is the repo the notebooks are being reviewed in, not the official jdat_notebooks repo.  Anyway, here are my comments from there- 

Ugh, Ignore the previous post (accidentally pressed Enter and github has no real delete function). I originally sent these comments to Matteo on slack, and he said the typical review process involves opening a ticket on github, which I assume meant issue. Since I originally sent everything on Slack, it's not particularly well formatted, but here are my comments:

The construction of the EPSF doesn't obviously seem to preferentially choose stars in any way. This is potentially something to look at, as I figure there's a tradeoff between number of stars used and the average SNR of those stars.

-It seems the peak of the distribution of detected stars is at approximately -5.5 mag (instrumental mag, not
exposure time corrected), but there are a fair number of stars brighter than that. Due to the rather undersampled nature of
the PSF, I'm thinking the signal in the wings of the PSF from the faint stars is fairly low, and often in the noise of the
background.

That's especially true since the radius of the constructed EPSF is ~12 pixels, so several FWHM. Not sure it's necessarily critical, but when we do PSF fits for WFC3/UVIS using the empirical PSFs, we only fit the innermost box of 5x5 pixels. For the IR I think it is the same, but I can't remember exactly. Generally we find this does a pretty good job, and allows for measurements of faint stars, without having low signal in the wings cause much issue. I think it may be worth looking at the number/brightness of stars used in the EPSF creation, as well as the size of the created EPSF.
That also has the added benefit of reducing effects on crowding. Obviously, not fitting the full extent of the PSF would require further correction afterwards, but this may be achievable as some form of "aperture correction". How much that aperture correction varies across the FOV and time will likely be the key determinant on whether this is a better strategy or not.

Another note I think is important is the creation of the gridded EPSF, I see that's in the todo list, which is great. For HST we find this to be pretty important as there is substantial variation across the FOV. With the EPSF builder already in place, creating these is probably fairly simple. The GriddedEPSFModel class is easy enough to instantiate, and it looks like there's the skeleton of some of that stuff already there. I know it's not exactly the same here, but we provide the gridded EPSF's for HST instruments, as we know they can be derived from other data and fit with decent results.
-In truth the best results come from the focus dependent EPSFs that we provide, and I have written a subclass of GriddedEPSFModel that handles them, but I wouldn't think that's in the scope of this. The point is that in the future it may be worth looking into providing PSFs already generated from good data, that is parametrized by focus or some other relevant variable.

-I think another useful thing to show may be the outputs of the PSF fitting, as in the catalogs before they go into the CMD's, just so users know what information is available. Comparing fits to groups containing multiple stars vs a single star, or even just commenting on the behavior there could be useful.
-Also showing what the uncertainties look like as a function of flux, and even position (since a single PSF is being used across the field), would be interesting, if only to show as a comparison to gridded model performance
-Showing the subtracted images are nice to show fit quality, but quantifying it with a single number may be good too. With Jay's PSF photometry/methods, we have a q parameter, which is computed as abs(Fit - data)/ (fit flux). Kind of shows how far "off" the data was from the model. This might not be the easiest to implement though.

-The last science related comment I have would be to also give some comment about the astrometric information that comes out of the fits. The benefits of the PSF fitting are often great when looking for accurate positions, and typically better than DAOFind type routines in my experience. A potential way to show this could be to plot the separations between the fit positions of the same stars in the two bands vs mag, to get some idea of astrometric precision. I think that will be very interesting to those looking to measure proper motions/detect microlensing etc.

-Last thing: for readability, putting a lot of the stuff that gets ran twice in a cell into a function could be nice. For instance the detection of stars, the fitting, and the matching of the stars can likely be condensed into functions, and just have lines later that call them. This is also nice because users can copy/paste the relevant functions right out for their own analyses.

**Comment by ibusko** [comment]
## Technical review (NIRCam_PSF_Photometry_Example.ipynb)

### Running the notebook

 - Notebook doesn't run to completion as provided.

     - pysynphot needs acces to TRDS data. /data1/trds-files is not mounted on VPN-connected
     nodes (at least not on mine). I had to copy it to a local directory.

     - PYSYN_CDBS variable needs to be added to the environment.sh file

     - cell 13 (webbpsf.gridded_library.display_psf_grid....) raises an exception
     (AttributeError: 'NoneType' object has no attribute 'data')
     This can be fixed with an additional run of the PSF build code with grid=True. This
     could be done be either adding a new cell that does that before calling the plotting
     cell, or by having just one kind of plot (the gridded one, perhaps), and adding text
     that would alert the user of the possibility of running the code in the other mode.

     - cell 28 displays a string error:
     File "<ipython-input-22-bdc2c65bb1e7>", line 77
         residual_outname = residual_%s_%s_webbPSF_gridPSF_level2_%dof%d_%dof%d.fits' %(d,filt, prim_dith_pos, prim_dith_num, subpx_dith_pos, subpx_dith_num)
         SyntaxError: EOL while scanning string literal


### Input data

  - Are properly stored in Box using redirect.


### Libraries

 - Currently available core-libraries functionalities and visualization tools are used.


### Developer notes

 - In the list of existing ipywidgets there ought to be something that fullfills the desired
   behavior. It may be worth to browse over that list just to acquaint ourselves with the
   variety of types. Maybe a combination of a dropdown or radio button to select the filter,
   and a IntSlider to rotate over the images can provide the desired behavior?

  https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html#Numeric-widgets


### PEP-8 compliance:

  - Running 'flake8' on the notebook cells results in this report

  cell  3 line  4: E127 continuation line over-indented for visual indent
  cell  3 line 25: E201 whitespace after '('
  cell  3 line 34: E303 too many blank lines (2)
  cell  3 lines 20,61,65: E231 missing whitespace after ','
  cell  4 line 6: E128 continuation line under-indented for visual indent
  cell  4 line 9 E231 missing whitespace after ','
  cell  4 line 25: E231 missing whitespace after ':'
  cell  6 lines 13,19: E231 missing whitespace after ':'
  cell  8 lines 1,4,9: E231 missing whitespace after ','
  cell  8 line  4: E272 multiple spaces before keyword
  cell  8 line  6: E117 over-indented
  cell  8 lines 14,16: E251 unexpected spaces around keyword / parameter equals
  cell  9 lines 4-6: E231 missing whitespace after ','
  cell 12 lines 1,4,5: E231 missing whitespace after ','
  cell 12 lines 8,10,11: E251 unexpected spaces around keyword / parameter equals
  cell 13 line 2: E251 unexpected spaces around keyword / parameter equals
  cell 13 line 2: E231 missing whitespace after ','
  cell 14 lines 4-6,12: E231 missing whitespace after ','
  cell 15 lines 6,9,10,19,27: E231 missing whitespace after ','
  cell 15 line 16: E251 unexpected spaces around keyword / parameter equals
  cell 15 line 28: E128 continuation line under-indented for visual indent
  cell 16 lines 7-9: E231 missing whitespace after ','
  cell 16 line 20: E225 missing whitespace around operator
  cell 16 lines 32,33,35,37,39: E251 unexpected spaces around keyword / parameter equals
  cell 17 lines 1,5,6: E231 missing whitespace after ','
  cell 18 line 1: E251 unexpected spaces around keyword / parameter equals
  cell 18 lines 3,7,17,19,37: E231 missing whitespace after ','
  cell 18 line 40: E231 missing whitespace after ','
  cell 18 lines 7,37,40: E225 missing whitespace around operator
  cell 18 line 23: F841 local variable 'flux' is assigned to but never used
  cell 19 lines 2,3: E231 missing whitespace after ','
  cell 19 lines 5,8: E251 unexpected spaces around keyword / parameter equals
  cell 20 lines 4-6,11: E231 missing whitespace after ','
  cell 21 lines 10,11,25,34,56: E231 missing whitespace after ','
  cell 21 line 39: E265 block comment should start with '# '
  cell 21 lines 49,53,57,62: E251 unexpected spaces around keyword / parameter equals
  cell 21 lines 54-57: E128 continuation line under-indented for visual indent
  cell 21 line 62: E225 missing whitespace around operator
  cell 21 line 68: E222 multiple spaces after operator
  cell 22 lines 3,10,22,25: E231 missing whitespace after ','
  cell 23 lines 4,8: E231 missing whitespace after ','
  cell 23 lines 5,9: E117 over-indented
  cell 24 lines 4,12,23,24: E231 missing whitespace after ','
  cell 24 lines 7,18: E128 continuation line under-indented for visual indent
  cell 24 lines 13,24: E251 unexpected spaces around keyword / parameter equals
  cell 25 line 5: E231 missing whitespace after ','
  cell 26 lines 1,17,18,28,29: E231 missing whitespace after ','
  cell 26 line 43: E225 missing whitespace around operator
  cell 26 line 18: E203 whitespace before ':'
  cell 26 lines 5-7,10-12: E128 continuation line under-indented for visual indent
  cell 26 line 28: E303 too many blank lines (2)
  cell 26 lines 39,41-43: E251 unexpected spaces around keyword / parameter equals
  cell 27 lines 3,5,20,35: E231 missing whitespace after ','
  cell 27 line 12: E222 multiple spaces after operator
  cell 27 lines 14,18,35,50: E128 continuation line under-indented for visual indent
  cell 30 lines 1,4,14,15,22,23,25,39,49,50,57,59,64,65,72: E231 missing whitespace after ','
  cell 30 lines 42,62: W605 invalid escape sequence '\s'
  cell 30 lines 6,7,22,23,37,41,42,57,61,62,72: E251 unexpected spaces around keyword / parameter equals
  cell 31 line 2: E127 continuation line over-indented for visual indent
  cell 31 lines 18,60,64: E231 missing whitespace after ','
  cell 31 line 24: E201 whitespace after '('
  cell 31 line 33: E303 too many blank lines (2)
  cell 32 lines 1,4,9: E231 missing whitespace after ','
  cell 32 line 4: E272 multiple spaces before keyword
  cell 32 line 6: E117 over-indented
  cell 32 lines 11,16: E251 unexpected spaces around keyword / parameter equals
  cell 33 lines 4-6: E231 missing whitespace after ','
  cell 34 lines 6,9,10,19,27: E231 missing whitespace after ','
  cell 34 line 16: E251 unexpected spaces around keyword / parameter equals
  cell 34 line 28: E128 continuation line under-indented for visual indent
  cell 35 lines 2,3,7,10: E231 missing whitespace after ','
  cell 35 line 8: E127 continuation line over-indented for visual indent
  cell 35 line 10: E251 unexpected spaces around keyword / parameter equals
  cell 36 line 5: E127 continuation line over-indented for visual indent
  cell 37 line 3: W605 invalid escape sequence '\s'
  cell 37 lines 3,10: E251 unexpected spaces around keyword / parameter equals
  cell 37 lines 5,10: E128 continuation line under-indented for visual indent
  cell 37 lines 4-8,10: E231 missing whitespace after ','
  cell 38 lines 16,57: E303 too many blank lines (2)
  cell 38 lines 5,24,25,34: E231 missing whitespace after ','
  cell 38 lines 26-28,38,49-54: E251 unexpected spaces around keyword / parameter equals
  cell 40 lines 1,4,17,25,26,34,37,50,58,59,67: E231 missing whitespace after ','
  cell 40 lines 35,68: W605 invalid escape sequence '\p'
  cell 40 lines 35,68: E228 missing whitespace around modulo operator
  cell 40 lines 6,7,33-35,39,40,66-68: E251 unexpected spaces around keyword / parameter equals
  cell 41 lines 3,5: E251 unexpected spaces around keyword / parameter equals
  cell 41 line 3: W605 invalid escape sequence '\s'
  cell 41 line 4: E127 continuation line over-indented for visual indent
  cell 41 lines 3,5: E231 missing whitespace after ','
  cell 43 lines 1,14,24,25,38,40,41,51,56: E231 missing whitespace after ','
  cell 43 line 18: E203 whitespace before ':'
  cell 43 lines 5-7,10-12: E128 continuation line under-indented for visual indent
  cell 43 lines 32,34-36,70,73,74,76,77: E251 unexpected spaces around keyword / parameter equals
  cell 44 lines 1,4,9,1119,26,2735,39,4453,60,61,69: E231 missing whitespace after ','
  cell 44 line 37: E225 missing whitespace around operator
  cell 44 line 70: E228 missing whitespace around modulo operator
  cell 44 lines 7,36,42,70: W605 invalid escape sequence '\D'
  cell 44 lines 36,70: W605 invalid escape sequence '\p'
  cell 44 lines 6,7,9,34,35,37,41,42,68-70: E251 unexpected spaces around keyword / parameter equals


### Build

 - There is a CI build error caused by the absence of TRDS (and its associated variable
   PYSYN_CDBS) in the build environment.


### Comments

 - It would be nice to have some text in the Import Functions section about the possible
   error one gets from pysynphot when PYSYN_CDBS is not defined in the user's environment
   prior to starting the jupyter server. The error should be fixable by sourcing the
   environment.sh file under the bash prompt (provided the variable is properly defined there).

 - Cells 4, 31: it would be nice if the code could check for the existence of input files and
   skip downloading if they are present.

 - Currently the pre-install.sh script throws the user out of bash.

**Comment by mcorrenti** [comment]
Thanks for your review @Vb2341 and @ibusko. Below my comments/replies:

- ePSFs stars are selected using as a criteria their brightness (i.e., the threshold in the daofind algorithm) and I also implemented a further criteria that allows to select “isolated” stars (no neighbor closer than X pixel, where X is fixed by the user). Obviously, the threshold and minimum acceptable distance depend on multiple factors as for example the number of stars in the field of view, crowding, minimum number of stars that the user want to use to build the ePSF, etc. Here, I provide just an example to show how, with the current functions present in PhotUtils, it is in principle possible to create an empirical PSF. The size of the ePSF is just to display them, in reality during the reduction what matters is the parameter _fitshape_ that determines the rectangular shape around the center of the star which will be used to collect the data to do the fitting. In the notebook, I’m using 11 px because the radius corresponding the EE=70% is ~ 4 px for the filters adopted, but it’s definitely a parameter that can be tweaked by the user and/or by us after trying with different values and compare the resulting photometry. In the next notebook update, I will use a different parameters if changing this value after further test suggest an improvement in the psf photometry quality.
- I agree that the best results come from using a gridded ePSF and, when we will have real data, with the focus dependent ePSF. I will definitely reach out to you in the future, when I will complete the work related to the gridded ePSF.
- I added a cell that shows the catalog obtained from the reduction, allowing the users to verify what parameters are obtained. I understand your point about comparing the different results obtained when different PSF model (single vs grid) are used (note that in the II part of the notebook I’m using the photometry obtained from a PSF grid), but I think it would be better to defer it to when we have actual data after commissioning. I would refrain to provide any comparison that can give biased or incomplete results or give the impression that one is better than the other of a factor X. Moreover, in the notebook, there’s also 1 example of the grid (with 25 WebbPSF PSFs) but the user could wonder why 25 and not 16, etc. The idea is to provide the framework and let the users experiment depending again on their science case. I added a note at the end of the notebook to summarize this discussion.
- I included a cell to show the residual images. I agree that having some sort of quality diagnostics would be good and for this reason I left a note in the notebook. My opinion is that it should be implemented in the psf photometry routine (like in Jay’s PSF photometry) rather than created a posteriori in the notebook.
- I included a comparison between X,Y position from daofind and psf photometry and as a function of the magnitude. I also included a final plot that compares RA,Dec between input and output photometry.
- I agree. Moved to function some of the stuff that is run twice (finding, building ePSF, psf photometry, etc.). 

- Included a note about pysynphot (need to download data files and set the environment variable).
- Fixed error about grid and single PSF adding a new cell that allows to create a grid of PSF (grid_psf=True).
- Included an “if” statement that allows to skip the download if the files exist in the current folder. 
- Verified PEP-8 compliance running flake8-nb on the notebook.

**Review by ibusko — APPROVED** [review]
Runs to completion and fulfills requirements.

**Pull request merged**
