### PR TITLE
Updated NIRISS/SOSS transit spectroscopy notebook for easier rendering

### PR DESCRIPTION
**Pull request by nespinoza**
Hi everyone,

 This PR comes as a response to some comments via Slack that the notebook was taking too long to render. This is because of the final lightcurve fits done in the second-to-last cell, which are very expensive. As a response, I've uploaded the results of those fits to Box, and now I simply download them in this notebook. 

 I've added this snippet to the notebook:

Screen Shot 2020-09-14 at 1 45 52 PM

By default, the notebook downloads the results to make the plots. However, if the user wishes so, they can simply set that flag to `False`, and run the fits on their own. Either way, both give the same results.

 I've also taken the chance to remove some pickle dumps and loads I was doing in the notebook for intermediate results (sorry for that!). But that's very minor.

 Let me know if this works for you folks!

 Best,
Néstor

### CODE REVIEW

**Comment by jbcurtin** [comment]
Would you change this into a ENVVar? 
```
use_downloaded_results = True if os.environ.get('USE_DOWNLOADED_RESULTS', 'true').lower() in ['t' ,'true'] else False
```

**Comment by nespinoza** [comment]
Hey @jbcurtin --- wouldn't that make that line, which is supposed to be very simple, a possibly very complicated line to read?

**Comment by jbcurtin** [comment]
It would make it harder to read, but then I could toggle the setting in the CI. If I'm understanding this correctly, and the default is to use the model from an URL by default. We won't need that alteration

**Comment by nespinoza** [comment]
Hi @jbcurtin --- indeed, the default is to use the model from an URL, so I think we don't need that alteration.

**Comment by jbcurtin** [comment]
The CI is passing, but this notebook isn't being built. Will you take it out of the excludes list?
https://github.com/nespinoza/dat_pyinthesky/blob/soss-transit-spectroscopy/excluded_notebooks#L3

**Pull request merged**
