### PR TITLE
niriss_ami_binary notebook 3

### PR DESCRIPTION
**Pull request by rcooper295**
AMI notebook 3 ready for review by technical and science reviewers

### CODE REVIEW

**Comment by rcooper295** [comment]
- [ ] Box:

    - [ ] Data has been uploaded to box.
    - [ ] The data is bing shared via link. Make sure the settings allow for anyone with a link to download.

- [ ] GitHub:

    - [ ] Notebook has all cell outputs cleared out.
    - [ ] Notebook is written in `Python 3`
    - [ ] All imports occur at the beginning of the notebook.
    - [ ] All data is loaded into the notebook via a URL from box. (No local files being used).
    - [ ] Verify that the python code satisfies PEP 8.
    - [ ] Comments and unused lines of code are removed.
    - [ ] `requirements.txt` file is included.

**Comment by camipacifici** [comment]
Hi All, is there any update on this notebook?

**Comment by rcooper295** [comment]
I noticed the environment setup files in main have changed (there used to be a pre-requirements.txt and requirements.txt file, now there is a pre-install.sh and environment.sh scripts in addition to requirements.txt file), so the instructions on environment setup in the beginning of all the niriss_ami_binary notebooks will probably need to be changed? I just cleared the output so it should be ready to merge for now, though updates will probably be needed soon.

**Comment by rcooper295** [comment]
@camipacifici I updated this notebook to use in-flight data (also updated contents of Box zip file). I also replaced candid via AMICAL with a direct import of candid, since it has been updated. This produces cumbersome output in some cells. I will add the new dependencies (candid, cython) to the jdat_notebooks repo requirements.txt file when this is ready to be migrated over there.

**Comment by camipacifici** [comment]
Thank you @rcooper295!!
@orifox, @TheRealZoidberg, @ojustino, I think this is ready to be moved to jdat_notebooks!

**Pull request closed without merging**
