### PR TITLE
Advanced Composite Model Fitting notebook

### PR DESCRIPTION
**Pull request by hcferguson**
Draft of notebook from @ibusko , annotated and partially revised by @hcferguson to use some of the SpecUtils machinery.

### CODE REVIEW

**Comment by eteq** [comment]
Aha!  I think the build is now working.  @hcferguson, can you confirm that https://26-126393017-gh.circle-artifacts.com/0/root/repo/jdat_notebooks/composite_model_fitting/specfit_demo_3.html looks the way you think it should look for this notebook?

**Comment by eteq** [comment]
Oh and one clarifying question for @hcferguson: in the requirements file you specified `==` for your versions.  Is that intended, or do you mean `>=`? I.e., you were specifying the version you are running on, but not saying that you know for sure it doesn't work on a more recent version.

(This also reveals that a bit more detail on what goes in the `requirements` file is called for in the README...)

**Comment by hcferguson** [comment]
The html rendering looks good to me.

Requirements >= should be fine. I was just mindlessly following the example.

**Comment by eteq** [comment]
> Requirements >= should be fine. I was just mindlessly following the example.

Oh good point!  I should change the example to be >=...

**Pull request merged**
