### PR TITLE
First version of the NIRISS/SOSS transit spectroscopy notebooks

### PR DESCRIPTION
**Pull request by nespinoza**
Hi everyone,

 Here are the transit spectroscopy notebooks for the NIRISS/SOSS transit spectroscopy case. As I mentioned in the meeting, there are three notebooks: the one to simulate the data (PART1), the one to calibrate the data with the JWST pipeline (through Stage 1 only; PART2) and the actual data analysis notebook (PART3). The latter one is the one that was the actual product for this JDAT sprint (I've been working on the others for a while).

 As can be seen, there are some things to fix still in the PART3 notebook (I've identified those as "Developer Notes" --- and all of them refer to some bugs to fix in the NIRISS/SOSS data simulator), but I think the overall notebook shape is pretty good. The files needed to run the notebook have been uploaded to the Box folder under `jwst-data_analysis_tools/soss-transit-spectroscopy`.

 Thanks for all the feedback!

Néstor

### CODE REVIEW

**Comment by dtn5ah** [comment]
Hi @nespinoza! I've been assigned to your PR for technical review! To get things started, could you create a requirements.txt file? I'm not sure if Robel spoke to you about it, but it contains all the packages necessary to create a brand new environment for your notebook to run. Let me know if you have any questions!

**Comment by nespinoza** [comment]
Hey @dtn5ah --- done in https://github.com/spacetelescope/dat_pyinthesky/pull/111/commits/3720d60ad47472dd423eb25540e17d4bda6a8540!

**Comment by dtn5ah** [comment]
Hi @nespinoza! I'm still working on your review (awesimsoss is giving me a huge pain installing, but I think I finally got through it). On cell 2 of your first notebook you write
> The corresponding (corrected) transit spectrum can be found in this repository under data/hp1_tspec.dat...

but I can seem to find it in this PR? Or am I missing something? 

Thanks!
Duy

**Comment by nespinoza** [comment]
Hi @dtn5ah! I have to amend that I believe; the transit spectrum should be on the Box folder associated to this Notebook under the `data` folder. Should I commit/amend that to the Notebook?

Néstor

**Comment by dtn5ah** [comment]
Oh I see, yes please @nespinoza! I was not going to bother you with the box upload just yet, but that would need to get done eventually so if you want to take care of that now, that would be great!

**Comment by nespinoza** [comment]
Hey @dtn5ah --- so, how should I put this in the Notebook? Should I just say "it is in the Box folder under (...)", or should I try to link it explicitly in the notebook? And if so --- how (e.g., create a shareable link?)?

**Comment by dtn5ah** [comment]
Oh my apologies @nespinoza, I had thought Robel had walked you through how to do this already. You can find instructions on how to upload your data here: https://github.com/spacetelescope/style-guides/blob/master/guides/where-to-put-your-data.md#obtaining-static-box-links

**Comment by skendrew** [comment]
This is a nice, very in-depth notebook. Here are some review comments. 

### General comments

- I was not able to actually _run_ the notebook, as I don't have access to the input data files. Also, I would have to install the Awesimsoss simulator and it's clear from the text that the pipeline processing on a standalone laptop is very time consuming and I would prefer not to tie up my machine for many hours. So my first comment is that this notebook is an excellent use case for the Jupyter Hub environment, which would be perfectly set up to host all the required tools and data.

- I have some questions about the scope of these data analysis notebooks. This particular case is a very in-depth science use case, starting from the data simulation to the post-processing analysis of the data, the latter stages of which are not JWST-specific and rely on an external package. So this is almost a mini tutorial for how to use `juliet`. If that is in scope for these notebooks, that is fine, but it does seem like this differs between some of the notebooks.

### Notebook 1

- Could do with a few words of explanation what the output of the transit model actually is? 

### Notebook 2

- There is not enough explanation about what the pipeline is doing in the detector1 stage; we don't have to go into it in detail in this notebook but we should link more to the readthedocs pages, which contain a lot of good background. [This page](https://jwst-pipeline.readthedocs.io/en/latest/jwst/pipeline/calwebb_detector1.html) for example is very useful for detector1.

- It's also worth stating that the explicit passing of the config file is only really needed if you're using simulated data, or want to re-process with a modified configuration. When the pipeline processes data coming in from the observatory, it will use the header keywords to select the appropriate configuration file.

- one of the strengths of the pipeline is the use of datamodels; the notebook should ideally illustrate how to read in pipeline products using the datamodels rather than FITS i/o.

- I'm not sure it's worth adding the "purely academic" exercise of verifying the ramp fitting. As we're finding in pipeline testing, it's actually quite difficult to emulate the pipeline's ramp fitting algorithm perfectly, so while this works well for this particular dataset the user may run into trouble when applying this same code to other data. There is [quite thorough documentation](https://jwst-pipeline.readthedocs.io/en/latest/jwst/ramp_fitting/description.html) on this step, so better perhaps to link to that? 

### Notebook 3

- maybe I missed it, but what is "BIC"?

- Is the spectral extraction demonstrated here similar to what is being proposed to put into the pipeline (in [JP-201](https://jira.stsci.edu/browse/JP-201))? Or is it an enhanced extraction method? I would not be in favour of replicating code here that is likely to go into the pipeline for cycle 1 while stating that the pipeline doesn't have the capability. If this is the case we should hold off releasing this notebook until the functionality *is* available so we don't have to write "the pipeline can't do this", and instead make sure the pipeline gets to meet this goal. If it is a more enhanced version of what is proposed in the above ticket, then we should present it as such.

- Would be good to show how to visualize the wavelength solution from the datamodels, you can see how to do that [here](https://jwst-pipeline.readthedocs.io/en/latest/jwst/assign_wcs/main.html) (but maybe this is not currently possible due to the pipeline still being under development?).

- The time series analysis portion of this notebook is really nice but see my above comment about the scope of the notebooks.

**Comment by robelgeda** [comment]
@dtn5ah @nespinoza : I believe the tests are failing because the some of the requirements in the requirement file are not included in the testing environment file. The testing environment file is at `dat_pyinthesky/jdat_notebooks/environment.yml` and the new required modules should be listed in there. Please check to avoid duplicates or conflicts as removing or editing modules already in the environment file will cause the test to fail (other notebooks will fail).

**Comment by skendrew** [comment]
looks really good @nespinoza, love the figures. I didn't really know what the scope of these notebooks was meant to be when invited to review (that's maybe feedback for @orifox!),  and I've since become aware that a lot of other notebooks are demo-ing non-JWST specific things - so that is clearly fine and the notebook looks great.

I have a few further comments, mostly minor and text corrections - so I'll leave it up to you what you consider worth correcting. I don't think any of them are blockers, the notebook would be fine as-is. 

inconsistent spelling of dependent vs dependant

section 1:

- familiarize -> familiarize _yourself_
- "on-the-making" -> "in-the-making"
- if this notebook is supposed to stand on its own, is it worth stating at the start to which level of pipeline the input has been processed? the filename doesn't have the pipeline suffix in it, so it's hard to tell. is it the _rate.fits file, or has it been through assign_wcs or any of the later spec2 steps?

section 2:
- I don't think "ramps" and "rates" are the same thing? Afaik the "ramp" is the per-group format(pre-deetctor1 processing), the "rate" is as you say the ramp-fitted output (or the "slope" image). or have I been getting that wrong all these years?
- In the text where you look at the format of the data, it may be worth pointing out that having the 3rd dimension with size NINT is a TSO-specific thing, i.e. for non-TSOs the integrations would get co-added and the format is 2D only.
- "on top of the this" -> on top of this
- "carreful" -> careful

2C:
- "let's you gain access" -> lets you gain access

section 3:
- "let's see how the fits look like" -> "how the fits look" or "what the fits look like"

section 4:
- "how does our transmission spectrum looks like" -> "how our transmission spectrum looks" or "what our transmission spectrum looks like"

**Comment by nespinoza** [comment]
All right folks, I answered all the points raised by @skendrew in her second review (thanks Sarah!).

On top of that, I've made three important changes in the notebook. The first two are aesthetic, the last one turned out to be of scientific importance, for which I'm thinking on writing up in a letter to MNRAS later this year. I've already mentioned this last one to @skendrew, so not sure these require an extra science review pass but **would love to get the "okay" from her anyways**:

1. **I changed the way in which the wavelength-dependent lightcurves are presented**. Before, I was presenting a couple of them and a couple of residual fits, which I thought was not very nice. I've changed that now to an actual _image_ where the x-axis is time and the y-axis is wavelength, with colors representing the relative flux. So, now, the wavelength-dependent lightcurves look like this in the native NIRISS/SOSS resolution:
Screen Shot 2020-09-10 at 10 17 38 AM I really think this is a much nicer way of showing the data in this case. Changed the same for the residuals:
Screen Shot 2020-09-10 at 10 18 44 AM As you see, it is evident from those two images that the transit modelling went pretty well. This way of showing the data also looks much, much nicer and shows _all_ the data, not only a portion of it.

2. **I now bin the wavelengths _after_ running the transit fits on the NIRISS/SOSS native resolution**. I think users will want to actually do this in actual observations --- I was being a bit "lazy" (as in, forcing the fits to run faster) by binning the fluxes and fitting those binned transit lightcurves, but users might be interested in narrow features that they'll have to access later in their transit spectrum only if they fit the lightcurves in the instruments' native resolution. The disadvantage of this is, of course, that the fits take _a ton_ of time (as in ~1.5-2 days) to run --- but this is stated in the notebook. I think this is _really_ good to mention, because this will prepare and make users aware that they need to paralellize those portions of the analyses if they want the results to be done in a shorter time-scale (as we'll be doing say, e.g., in commissioning for instance).

3. **I changed the limb-darkening law being used to fit the data**. Turns out this matters _a lot_ for JWST observations. As you see, the precision is much nicer now that this is done --- and I think I understand exactly why. The basic idea is that JWST observations will be so precise, that it is unclear if we should be using model prescriptions for limb-darkening from stellar model atmospheres. In this notebook, I'm actually _fitting_ for the limb-darkening effect through two coefficients (`q1` and `q2`), but it turns out that the limb-darkening law that you use for this matters and impacts the precision of your final transit spectrum. The precision that I obtain now matches more or less that from PandExo, whereas the limb-darkening law that I was using before (the quadratic law) gave rise to x2 the errors. Here's the interesting bit: the simulations _where injected using a quadratic limb-darkening law_. I found out that the problem is in the choice of priors (and perhaps other geometrical effects), so this is what I'm going to be writing up later this year as a letter. This has no impact for proposal preparation (and hence why I'm not rushing to get this out) --- but it does have a large impact for data analysis.

Hope this is not too much of a headache. Entering now to the technical review at 11 AM EDT!

Thanks,
Néstor

**Comment by skendrew** [comment]
thanks for the update @nespinoza - all looks good to me. the limb darkening update is really interesting, should be v useful to the community.

**Review by robelgeda — APPROVED** [review]
The notebook is PEP8 Compliant and ran on my local machine. Very well documented as well. 

### Major Changes During Review

- Pointed data download to box url instead of local path for one of the spectrum models.

**Pull request merged**
