### PR TITLE
MOS spectroscopy notebook

### PR DESCRIPTION
**Pull request by camipacifici**
This is the notebook where we showcase basic spectroscopy tasks using the specutils functionalities.

### CODE REVIEW

**Comment by eteq** [comment]
@camipacifici - looks like the last commit got the dependencies working!  The error now looks to be because the path just needs to be updated to the data links.

Note that `fits.open` understands URLS, so if the files are now all in the relevant place, I think you can just change `observedfiles = 'path-to-folder/observed/'` to `observedfiles = 'https://data.science.stsci.edu/redirect/JWST/jwst-data_analysis_tools/mos_spectroscopy/'`.

**Comment by hcferguson** [comment]
Looks excellent overall!  

A few general comments...

1. I think it would be good to flag the notes for the development team with the subtitle '##### developer note' in the markdown. This might make it easier to track them as the notebooks evolve.
Since one of the goals of these early notebooks is to help figure out what sorts of interactive visualization are useful in Jupyter notebooks, I'd suggest heavily annotating with developer notes about what interactivity you'd find useful.

1. The notebook might benefit from a bit more description of the data up front, for people not familiar with LEGA-C. It would also be good to describe the templates when you get to using them.

1. In many ways *lines* in 1D spectra are analogous to *sources* in 2D images.  And *regions* are similar to *apertures*. `Photutils` has several classes and methods for dealing with sources and apertures, that let you do operations on lists of these, like making cutouts, or iterating over measurements and fits. @nmearl @larrybradley @eteq -- can/should we consider using similar terminology for methods that are in common between these packages?

**Comment by hcferguson** [comment]
Cell 7 -- it would be good to include developer notes here on desired interactive features. Things that come to mind include:

- Auto scale 
  - I find setting `vmin,vmax` at the 1% and 99% levels generally works
- Auto label with units 
- Hover tool for cursor read back
- standard zoom, pan, stretch, change-colormap
- ability to drag out into a separate window (e.g. using goldenlayout?)

**Comment by hcferguson** [comment]
Cell 15: 
Should we heed the warning to use linear fitters? Or suppress it?

**Comment by hcferguson** [comment]
Cell 16: 
Add titles to the plots.

**Comment by hcferguson** [comment]
Cell 17: The markdown subtitle is `Creating the new normalized spectrum` but it is continuum-subtracted for the next few cells. Only normalized much further down.

**Comment by hcferguson** [comment]
Cell 22:

- Use alpha=0.5 for the line overlays? 
- Use `label=` and `legend` to label the spectrum and lines?

**Comment by hcferguson** [comment]
Cell 23:
Developer notes -- 

- Might be useful to have a line-inspection widget to cycle through zooms on each of the lines. Both for inspecting detection and inspecting fits.

**Comment by hcferguson** [comment]
Cells 27-28:
Developer note: Fitting lines with Gaussians is so common that it might make sense to have a one-line to iterate this over the list of lines, with sensible initialization of parameters and fit ranges for each line (e.g. based on @ibusko's code) so that the fits generally work.

**Comment by hcferguson** [comment]
Cell 32: The y-axis in the second plot is uncertainty.

**Comment by hcferguson** [comment]
Cell 35: The template comparisons can probably be parallelized within specutils. Is that already being done?

**Comment by hcferguson** [comment]
Cell 37:

- Use `alpha=0.5` for the overlay? 
- Add a legend.

**Comment by hcferguson** [comment]
That's it for my review...great notebook!

**Pull request merged**
