### PR TITLE
Fixes to spectral extraction notebook

### PR DESCRIPTION
**Pull request by eteq**
This PR makes several tweaks to the spectral extrraction notebook.  More specifically:

1. Removes the use of `ioff` and `plt.show` - that does not play consistently with some browsers - this PR instead skips `ioff` *and* `show`, depending on the `interactive` mechanism to show the figures automatically.  It's possible this breaks something I'm missing, but it looked fine to me, and without this PR instead there are several "blank" figures. (There's a third solution to this but I won't suggest it unless it's needed)
2. Mentions the big red error that comes up if you need to do the webbpsf data download. The first external user who tried this thought something was broken when they saw that warning, so it needs attention.  (and adds a developer note that relates this to spacetelescope/webbpsf#380 )
3. Moved the webbpsf import down to the appendix.  This is good because I foresee many users not wanting to go all the way to the second appendix and they shouldn't need to have webbpsf installed if so.

cc @gkanarek @robelgeda

### CODE REVIEW

**Comment by eteq** [comment]
I made this a DRAFT PR because I think @gkanarek is currently working on some fixes in the meantime. I can merge this with those when the time comes so you don't have to deal with merge headaches, @gkanarek .

**Comment by eteq** [comment]
I also noticed this notebook has a section labeled ""Fit Geometric Distoirtion (skipped)" - I'm not sure why it's there if it's supposed to be skipped, but I can add a commit to remove it if that's what's inteded.

**Comment by gkanarek** [comment]
Hi Erik, I have my updated versions ready, should I make a new PR or should I submit them on here?

**Comment by eteq** [comment]
Alright, the changes here were picked up in #121, so I'm closing this without merge since it's already there.

**Pull request closed without merging**
