### PR TITLE
Read the Doc Documentation for dat_pyinthesky

### PR DESCRIPTION
**Pull request by robelgeda**
This PR introduces a Read the Docs (RTD) page for this repo. We plan to use this RTD pages to provide instructions on how to contribute and cheat sheets to make the coding experience smoother.

As of now, this PR only adds documentation functionality and pyinthesky logos. The documentation is based on the STScI template. I have added some text as a place holder for instructions (which will be introduced later in a separate PR). The build is passing on my fork and the resulting page can be viewed at the following link:

https://robel-dat-pyinthesky.readthedocs.io/en/docs/

Please note that I will delete the RTD pages connected to my fork as soon as this PR is merged.

### CODE REVIEW

**Review by eteq — COMMENTED** [review]
This mostly looks good to me, except for one thing: the content in the index.html looks to be mostly copied-and-pasted from https://github.com/spacetelescope/dat_pyinthesky/blob/master/jdat_notebooks/README.md . To limit duplication (and the inevitable "I updated one but forgot to update the other"), maybe use the ``.. include::`` directive (https://docutils.sourceforge.io/docs/ref/rst/directives.html#include). That lets you include the content of one file in another.

The one awkward thing there is that the README is currently markdown not rst.  But there *is* a sphinx plugin to address that: https://www.sphinx-doc.org/en/master/usage/markdown.html .  Or alternatively, you can change the readme to `.rst`, since the primary reason for it is have it appear on github, which renders both `.md` and `.rst` pretty much equally.

**Comment by robelgeda** [comment]
> This mostly looks good to me, except for one thing: the content in the index.html looks to be mostly copied-and-pasted from https://github.com/spacetelescope/dat_pyinthesky/blob/master/jdat_notebooks/README.md . To limit duplication (and the inevitable "I updated one but forgot to update the other"), maybe use the `.. include::` directive (https://docutils.sourceforge.io/docs/ref/rst/directives.html#include). That lets you include the content of one file in another.

Not duplicating things makes sense to me, for now it is there as a place holder. But part of the plan is not to leave anything outside of the documentation folder, even in the repo. We want to concentrate all the info into the docs and this information looks like it should also be included there. So in the next PR, which will introduce actual content, we can move this out of the README and leave a link in the READ me to the docs. 
 

> The one awkward thing there is that the README is currently markdown not rst. But there _is_ a sphinx plugin to address that: https://www.sphinx-doc.org/en/master/usage/markdown.html . Or alternatively, you can change the readme to `.rst`, since the primary reason for it is have it appear on github, which renders both `.md` and `.rst` pretty much equally.

Sounds good to me. 

P.S: This PR is just so I can finish setting up the RTD for this repo.

**Review by rosteen — APPROVED** [review]
Looks good to me, all the build machinery and such for the docs worked when I tested it (which I gather is the point of this PR, not the actual docs page content).

**Review by ibusko — APPROVED** [review]
I was able to build and see the documentation as expected.

**Pull request merged**
