### PR TITLE
Specviz notebook-GUI interaction

### PR DESCRIPTION
**Pull request by camipacifici**
This notebook works with the jdaviz version in @rosteen PR https://github.com/spacetelescope/jdaviz/pull/380

I will include a requirement file when this PR gets merged.

### CODE REVIEW

**Comment by camipacifici** [comment]
Now the notebook works with the latest dev version of jdaviz and specutils.

**Review by PatrickOgle — CHANGES_REQUESTED** [review]
Here is the science review for this notebook.  The notebook is in pretty good shape and I was able to run all of the cells. Nice work!

 I have a few suggestions on content. Suggestions 2 and 5 are  optional, but the others should definitely be addressed:

1) Add an Introduction describing what the notebook does.
2) Maybe load only 3 of the NIRISS spectra to reduce confusion?
3) Give more guidance on what spectral region to select in specviz.  For example: 'Select a spectral region at 1.4 - 1.5 um that contains an emission line. The region is specified further down, but this suggestion could be between cells 6 and 7.
4) Use a try-except statement to circumvent the case where the user (or CI) does not  manually select a region in specviz.
5) The notebook covers region selection, line list, and redshift.  Is there more functionality we could showcase? Thoughts: Model fitting, line analysis....but maybe these are already covered in other notebooks?

I will be happy to review future changes...

**Comment by rosteen** [comment]
Looks good overall, I pretty much agree with Patrick's comments (there is a little bit of overlap between his comments and mine). My notes are mostly about the markdown/instructions rather than the code:

- The note at the top "In environment jdaviz_jan21 from github current version" should be removed.

- Presumably if someone is reading the notebook they already have jupyter installed, but since you say to create a new environment it's probably worth mentioning that they need to install jupyter in the new environment.

- I think the non-import parameter setting lines should be moved to a separate cell after the import cell.

- Also consider adding a little more detail about the imported packages in a markdown cell as in https://github.com/spacetelescope/style-guides/blob/master/guides/jupyter-notebooks.md#imports.

- "We find our favorite spectrum and work with that." - tell the user explicitly which spectra to deselect/leave selected. From later code I can see it's number 6 that we want to work with, but say that here.

- In general, a lot of the comments/headings seem like "thoughts to yourself" as the writer rather than addressing the reader. This is really just a stylistic thing, and I could go either way on whether to change it or not (I actually generally like the use of first person in scientific writing).

- Related to the above, places it would definitely be clearer to address the reader directly are when there are instructions the reader is intended to follow. It isn't clear that the line "I select the emission line by hand[...]" is an instruction for the reader to use the region selection tool in the notebook to select the region. Expand these instructions to be clear about what the reader is expected to do. 

- For the spectral lines, I recommend loading the three specific lines you mention in a notebook cell via the code-based line machinery rather than expecting the user to figure it out on their own/do it in the UI. Maybe load the lines in the cell and then point the user to the docs (as you do already) and pooint out the location in the plugin UI where they can see the lines they loaded. Especially since the redshift slider is slow with many lines loaded - we don't want the user to load a whole list with 100+ lines and then have the slider be slow. 

- Needs the STScI footer, see https://github.com/spacetelescope/style-guides/blob/master/guides/jupyter-notebooks.md#footer

**Comment by camipacifici** [comment]
Thank you for the reviews!
I committed a new version addressing, I think, all of your comments.

@PatrickOgle @rosteen Please have a look when you can. Thanks!

**Comment by camipacifici** [comment]
...and with cleared notebook now...

**Review by PatrickOgle — APPROVED** [review]
Hi Cami.  Looks great.  I was able to run the notebook including the interactive parts.
The instructions are clear and easy to follow.  Nice!

**Review by rosteen — APPROVED** [review]
Looks good to me!

**Pull request merged**
