### PR TITLE
ASDF example notebook

### PR DESCRIPTION
**Pull request by hcferguson**
A few examples of working with ASDF, using a FITS file as a starting point.

### CODE REVIEW

**Comment by perrygreenfield** [comment]
A couple of general comments; actually more like questions:

1) A tuple for fits value, comment is simple of course. An alternate would be an object that has a value and comment (description?) attribute so that one would access as tree['CRVAL1'].value and tree['CRVAL1'].comment. There are plusses and minuses to either and I don't have a strong feeling about this, but thought I would at least raise the alternative.

2) Should we just provide the simple WCS conversion tool rather than have to show the details in this example? To start at least deal with the CD matrix (or PC case) and a TAN projection? And possibly throw SIP in?

**Comment by nden** [comment]
I mentioned there are functions in gwcs which create the FITS WCS linear and non-linear transforms in the most common cases.

```
from gwcs import utils

transform = utils.make_fitswcs_transform(header)
```

**Comment by hcferguson** [comment]
> A couple of general comments; actually more like questions:
> 
> 1. A tuple for fits value, comment is simple of course. An alternate would be an object that has a value and comment (description?) attribute so that one would access as tree['CRVAL1'].value and tree['CRVAL1'].comment. There are plusses and minuses to either and I don't have a strong feeling about this, but thought I would at least raise the alternative.

I think this may be a more general issue to think about for ASDF. Having a standard (or alternatively "convention") on how to add annotations to each key-value pair in the tree would be useful even if you aren't starting from the FITS file. And then I think it would be nice to have an option on writing (maybe even the default) to copy the descriptions from the schema into these annotations, so that the meaning of the keywords is annotated in the file itself rather than buried in the schema.

**Comment by hcferguson** [comment]
> I mentioned there are functions in gwcs which create the FITS WCS linear and non-linear transforms in the most common cases.
> 

Thanks! Should I change my example to use that, or wait until it is documented in the gwcs docs?

**Comment by perrygreenfield** [comment]
I could see it as generally useful as well. More of a pain to use for values (but assignment could be just like parameters, just assign a value directly to the object). As for the name of the object: AnnotatedValue (or AV for short)?

**Comment by larrybradley** [comment]
This notebooks has already been moved to https://github.com/spacetelescope/jdat_notebooks

**Comment by hcferguson** [comment]
Adding Russell Ryan's comments & my replies here for safekeeping...to be addressed in future revisions.

> 1. do you need a context manager in opening th fits file?  or  just use fits.close() ?

Yes, that would be better. I’m usually sloppy about this in my own notebooks.

> 2. similar question for the asdf.open('myfile.asdf') call? do you need to close the asdf file?

Yes, that would be better. 

> 3. in Example 2 the meta data value, description pairs are tuples, whereas  in all subsequent examples they appear as lists.  Is this the  expected behavior?

Hmm…good catch. I’ll have to ask the ASDF experts about this.

>    3b. on a hunch,  was able to do things like
>      ` ff.tree['DATAMIN'].append(5)`
>      since ff.tree['DATAMIN'] is now a list:
>      `print(type(ff.tree['DATAMIN']))`
       
>       Then I wrote that file out, and it seems as if asdf ignores the higher indices, so I guess that's a good thing (but I'm always a bit concerned that I don't know asdf well enough to know that I wrote the modified DATAMIN out correctly).  This seems like an asdf thing, and not germane to your example, so I don't think you should worry too much about it.  But, it seems bad to me to have asdf change the datatype, particularly from an immutable to a mutable type.  Do you agree?  And if so, what is the proper way to provide that feedback to Perry and/or the asdf team?

Also a good catch. The proper way is to file an issue. But I’m on the periwinkle scrum team
so I can ask about this and the above in our next tagup.

> 4. In the preamble to Example 6, you might consider adding the word "celestial" to the phrase: "... mappings between detector and celestial coordinates."  Or does gwcs do something even more general transformation?

In principle gwcs doesn’t need to know that one end of the pipeline corresponds to “detector” and
the other “sky”. 

> 5. I got this warning:
> `/Users/rryan/miniconda3/envs/astroconda37/lib/python3.7/site-packages/astropy/wcs/wcs.py:2739: RuntimeWarning: cdelt will be ignored since cd is present
  description.append(s.format(*self.wcs.cdelt))`

> when runing the line 'fitswcs = WCS(header1)' in example 6. You sort of  touch on this issue in the description, but maybe just add something like, "Since both the PC and CD description are present, we will take the PC description as the truth and WCS will give a warning that can be disregarded."

Yes, good point.

> 6. This is a personal petpeeve of mine with Python...  But I really dislike how it uses the transpose for ndarrays --- and before I realized this, this was an endless source of pain.  Maybe remind readers of that when you display the image in the text?  Or perhaps put RA/Dec labels on the plotted galaxy images?

That’s a good thing to add in the next revision. I thought about doing it initially, but
I think the best package for that is aplpy and I was reluctant to create that dependency.

> 7. Does asdf also work well in storing tabulated data, akin to the fits tables?  If so, is that hard to add?  Or just do that in a separate notebook?

You can serialize astropy tables to asdf. That would be a good example to add.

**Pull request merged**
