### PR TITLE
First commit of PSF photometry Notebook

### PR DESCRIPTION
**Pull request by mcorrenti**
First draft version of the PSF Photometry Notebook

### CODE REVIEW

**Comment by larrybradley** [comment]
@robelgeda While reviewing this notebook, I discovered that `pip install webbpsf` fails.  Is that a known issue?

**Comment by robelgeda** [comment]
Hi Larry it should work. I just ran it on my personal machine and it was successfully installed using `pip`

**Comment by JayVB** [comment]
I've been asked to write a review as well.  I'm not a python person yet.  I've taken some classes and thought it would be easy to get the notebook up and running.  I did manage to get the notebook running.  It made it through the image-download stage and the sub-array extraction stage, but it crashed when the next block needed photutils.  I tried to install the package, but it gave me command-line problems that I'll need help to resolve, and since I'd like to get this to you ASAP, I'll wait on that.
 
I do find the code very readable and it's additional inspiration for me to learn more python... I'm getting less intimidated as time goes on.  But I don't think I'll be able to give it a full technical review until I get my python issues resolved.  I hope it's ok that I just read it over and am providing comments with the understanding that the figures look like I assume they will look.
 
Once the CTE project is out of my hands, I am planning on getting into python tools for my own functional work, and maybe even science, so I'll be in a better position to review and provide more technical comments on things like this.  I am hoping that there will be a good synergy between HST and JWST in this respect.
 
So, here are my comments:  
 
Overall, I think it is a very nice demonstration of how to do the basic things that most people will want to do.  There are some things that are TBD, but even without all those things fleshed out, I think it would be useful to show this to the community so they can start thinking about what reducing JWST data will involve.
 
Here are more detailed comments:
 
images background --> image backgrounds  (no plural adjectives in english... or did you mean image's background?)
 
to limit *its* runtime
 
we show how *it* is possible...
 
Good caveats about how to remove stars from contributing to the PSF... this is hard to do in an automated way sometimes, since it's not always clear what kind of threshold to use to reject stars. Sometimes you can say if their fit is 3x worse than the median star, but even then it can be hard to define a good "fit" metric.  I think the caveat you give is good and adequate for the current purpose.
 
Aside:  It's certainly true that you can't build an astrometrically accurate PSF without reducing multiple dithered images at the same time, but that's clearly beyond of the scope of this exercise.  I don't think there's anything set up in photutils to do this yet.  This PSF treatment should be adequate for high-precision photometry, provided there are no intra-pixel sensitivity issues.  Not sure if this needs to be mentioned explicitly.
 
I think the plural of "ePSF" is ePSFs ; there are several places where you mean the plural rather than the singular.
 
I think the slowness of the routine when operating on a whole image will be a concern, particularly as this is just one exposure, and not a set of dithered exposures.  Are there any efforts underway to speed things up?  I think before this notebook gets released to the public, then we should be able to tell the community what solutions are in the works for that.   Perhaps specialized low-level code will have to be written to do some things.  It shouldn't be too hard to implement a quick gradient search for the optimum (x,y,z) (where z=flux) for a star by fitting to the 5x5 pixels around its center.  Perhaps this is what the LevMarLSQFitter does, but perhaps there's a lot of overhead in using the fitter and in the end it's not as efficient as a specialized tool.  This is just speculation on my part.
 
From one of the blocks, it sounds like WebbPSF is able to simulate PSFs at different locations in the field.  It will be interesting to assess how rapidly the PSF changes with location on the detector, just from this theoretical tool.  That can be a useful thing for people to know.  In general, building up a PSF from scratch from a single image is probably not the best way to do this.  In general, one might want to start with a "library" PSF, either extracted from actual images or taken from WebbPSF, where you have a nice array of PSFs across the detector.  The routine could then start with this backbone PSF, which could contain much of the spatial variability, and perturb it to better match the stars in the image.  Often, you have full spatial variability (say 10x10) in the backbone model, and lower spatial variability (say 3x3) in the perturbation.  This is something that could be explored at some other time.  I'm not suggesting it for this, just for something to consider going forward.  Most of my HST stuff is based on this; rarely do I construct a complete PSF from data in-hand.  I usually start with a PSF that I extracted from a set of images with a good dither and lots of stars per PSF zone.
 
Overall, I think think this is a very nice demonstration of how to use the tools that are under development.  I think this already does a lot of good things, but I'm excited to see how it will be filled out even further.

**Comment by larrybradley** [comment]
@JayVB How were installing `photutils`?  If you are using a conda environment, you should be able to do `conda install photutils -c astropy`.  If you are not using conda, then `pip install photutils` should work.

**Comment by larrybradley** [comment]
To close the loop, `conda install photutils -c astropy` worked for @JayVB.

**Comment by mcorrenti** [comment]
@larrybradley @robelgeda @JayVB @camipacifici 

Thanks for your technical and scientific reviews. In the updated version of the notebook, I made the following changes/updates:

- imported all libraries at the top of the notebook
- removed commented file paths
- fixed all typos
- removed "DO NOT RUN CELL BELOW" and substituted with the sentence "to run the photometry on the full field, uncomment cell below" (keeping the warning about runtime)
- use np.transpose in 10th cell (weird, I used np.transpose a couple of cell above, don't know why didn't use it here)
- add a cell to divide the image using keyword "PHOTMJSR" from image header (from Mjy/sr to cps)
- remove note about xy match

**Pull request merged**
