### PR TITLE
Initial notebook for NIRCam photometry

### PR DESCRIPTION
**Pull request by dancoe**
Initial notebook for NIRCam photometry

### CODE REVIEW

**Comment by eteq** [comment]
As a quick note here: I see this notebook required implementing a `` function.  Was the functionality outlined in https://docs.astropy.org/en/stable/units/logarithmic_units.html#arithmetic-and-photometric-applications not sufficient? If not it's an area ripe for improvement, but I wanted to mention it just because it might be little-known...

**Comment by larrybradley** [comment]
Dan also discovered what I think is a bug in serializing ABmag units.  I need to report this upstream in astropy:

```python
>>> import astropy.units as u
>>> from astropy.table import QTable
>>> tbl = QTable()
>>> tbl['ABmag'] = np.arange(3) * u.ABmag
>>> print(tbl)
 ABmag
mag(AB)
-------
    0.0
    1.0
    2.0
>>> tbl.write('magnitudes.ecsv')
RepresenterError: ('cannot represent an object', Unit("mag(AB)"))
```

**Comment by larrybradley** [comment]
As a followup, the `ABmag` serialization bug was reported to `astropy` last May.
https://github.com/astropy/astropy/issues/8653

**Comment by eteq** [comment]
> As a followup, the ABmag serialization bug was reported to astropy last May.
astropy/astropy#8653

Note there's now a PR to fix that bug: https://github.com/astropy/astropy/pull/9933

Working on the assumption that's going to get merged, would that change the approach here?

**Pull request closed without merging**
